# Configuration commune aux 3 sentinelles
port 26379
# Surveiller le master "mymaster" ; quorum = 2 sentinelles d'accord
sentinel monitor mymaster 172.31.0.10 6379 2
# Master déclaré injoignable après 5 s sans réponse
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 15000
sentinel parallel-syncs mymaster 1
